#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

getc()
{
	stty raw
	tmp=`dd bs=1 count=1 2>/dev/null`
	eval $1='$tmp'
	stty cooked
}

press_any_key()
{
	echo -n "Strike any key to continue ..."
	getc anychar
}

echo -n "Enter a character:"
getc char
echo
echo "You entered $char "
press_any_key char
echo
